baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Eli's eclectic elucidations"
theme = "hugo-bearcub"
enableRobotsTXT = true
[params]

  # The description of your website
  description = "A blog and portfolio website for Eli Dowling"

  # This title is used as the site_name on the Hugo's internal opengraph
  # structured data template
  title = "Eli's eclectic elucidations"

  themeStyle= "herman"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true
